/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mysql.jdbc.log.Log;
import controle.SharedPEmpresa_Control;

import controleService.ControleLogin;
import controle.SharedP_Control;
import controleService.ControleCargo;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.CargoBEAN;
import modelo.FuncionarioBEAN;
import modelo.local.SharedPreferencesBEAN;
import modelo.local.SharedPreferencesEmpresaBEAN;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import retrofit2.http.Headers;
import sync.RestauranteAPI;
import sync.SyncDefault;
import util.Criptografia;
import util.ManipularImagem;
import visao.util.AlertDialog;
import visao.util.Carregamento;

/**
 *
 * @author Daniel
 */
public class FRMLogin extends javax.swing.JFrame {

    private ControleLogin c = new ControleLogin();
    private ControleCargo contCargo = new ControleCargo();

    /**
     * Creates new form FRMLogin2
     */
    public FRMLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        SharedPreferencesEmpresaBEAN e = c.listarEmpresa();
        if (e.getEmpCodigo() == 0) {            
            FRMLoginEmpresa le = new FRMLoginEmpresa();
            le.setVisible(true);
            this.setVisible(false);
            
        } else {
            setDados();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbFantasia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jpfSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lnTitulo = new javax.swing.JLabel();
        usu = new javax.swing.JLabel();
        sen = new javax.swing.JLabel();
        chekLogado = new javax.swing.JCheckBox();
        lbCadastro = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbCadastro1 = new javax.swing.JLabel();
        lbConf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        lbFantasia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbFantasia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFantasia.setText("Empresa Logada");
        jPanel2.add(lbFantasia);
        lbFantasia.setBounds(10, 10, 490, 100);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jpfSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jpfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfSenhaActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setMaximumSize(new java.awt.Dimension(105, 25));
        btnLogin.setMinimumSize(new java.awt.Dimension(105, 25));
        btnLogin.setPreferredSize(new java.awt.Dimension(105, 25));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginjButton6ActionPerformed(evt);
            }
        });

        lnTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lnTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lnTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnTitulo.setText("LOGIN");

        usu.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        usu.setText("Email-Usuario:");

        sen.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        sen.setText("Senha:");

        chekLogado.setBackground(new java.awt.Color(255, 255, 255));
        chekLogado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chekLogado.setSelected(true);
        chekLogado.setText("Lembrar-me login");
        chekLogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekLogadoActionPerformed(evt);
            }
        });

        lbCadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbCadastro.setForeground(new java.awt.Color(0, 0, 204));
        lbCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCadastro.setText("Não possui cadastro, Clique aqui !!");
        lbCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCadastroMouseExited(evt);
            }
        });

        jtfUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chekLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpfSenha)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                    .addComponent(usu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lnTitulo)
                .addGap(63, 63, 63)
                .addComponent(usu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(sen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chekLogado)
                .addGap(56, 56, 56)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lbCadastro)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(720, 40, 460, 620);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logotipo4.jpg"))); // NOI18N

        lbCadastro1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbCadastro1.setForeground(new java.awt.Color(0, 0, 204));
        lbCadastro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCadastro1.setText("Trocar de login....");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbCadastro1)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 510, 660);

        lbConf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gear.png"))); // NOI18N
        lbConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbConfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbConfMouseExited(evt);
            }
        });
        jPanel2.add(lbConf);
        lbConf.setBounds(1300, 0, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginjButton6ActionPerformed

        if (!jtfUsuario.getText().equals("")) {
            if (!jpfSenha.getText().equals("")) {
                if (jtfUsuario.getText().equals("admin") && jpfSenha.getText().equals("admin")) {
                    FRMPrincipal p = new FRMPrincipal();
                    p.setVisible(true);
                    dispose();
                } else {
                    fazLogin(jtfUsuario.getText() + "", Criptografia.criptografar(jpfSenha.getText()));
                }

            } else {
                JOptionPane.showMessageDialog(null, "Insira sua senha");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insira um email");
        }

    }//GEN-LAST:event_btnLoginjButton6ActionPerformed

    private void jpfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfSenhaActionPerformed
        btnLoginjButton6ActionPerformed(evt);
    }//GEN-LAST:event_jpfSenhaActionPerformed

    private void lbConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConfMouseEntered
        lbConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gearF.png")));
    }//GEN-LAST:event_lbConfMouseEntered

    private void lbConfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConfMouseExited
        lbConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gear.png")));
    }//GEN-LAST:event_lbConfMouseExited

    private void lbCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastroMouseEntered
        lbCadastro.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbCadastroMouseEntered

    private void lbCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastroMouseExited
        lbCadastro.setForeground(new Color(0, 0, 204));
    }//GEN-LAST:event_lbCadastroMouseExited

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void chekLogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekLogadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chekLogadoActionPerformed

    private void lbCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCadastroMouseClicked
        FRMFuncionario f = new FRMFuncionario();
        f.setVisible(true);
    }//GEN-LAST:event_lbCadastroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chekLogado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lbCadastro;
    private javax.swing.JLabel lbCadastro1;
    private javax.swing.JLabel lbConf;
    private javax.swing.JLabel lbFantasia;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lnTitulo;
    private javax.swing.JLabel sen;
    private javax.swing.JLabel usu;
    // End of variables declaration//GEN-END:variables
//private UJComboBox comboUsuario;
    public void tipoLogin(int cargo) {
        FRMPrincipal p = new FRMPrincipal();
        FRMPrincipalCaixa p1 = new FRMPrincipalCaixa();
        FRMPrincipalGarcom p2 = new FRMPrincipalGarcom();
        FRMPrincipalGerente p3 = new FRMPrincipalGerente();

        Carregamento a = new Carregamento(this, true);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                a.setVisible(true);
            }
        });
        SharedPreferencesEmpresaBEAN sh = SharedPEmpresa_Control.listar();
        RestauranteAPI api = SyncDefault.RETROFIT_RESTAURANTE.create(RestauranteAPI.class);
        System.out.println(sh.getEmpEmail() + "/" + sh.getEmpSenha());
        final Call<ArrayList<CargoBEAN>> call = api.listarCargos(sh.getEmpEmail(), sh.getEmpSenha());
        call.enqueue(new Callback<ArrayList<CargoBEAN>>() {
            @Override
            public void onResponse(Call<ArrayList<CargoBEAN>> call, Response<ArrayList<CargoBEAN>> response) {
                System.out.println(response.code());
                if (response.code() == 200) {
                    String auth = response.headers().get("auth");
                    if (auth.equals("1")) {
                        System.out.println("Login correto");
                        ArrayList<CargoBEAN> u = response.body();
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                a.setVisible(false);
                                for (CargoBEAN c : u) {
                                    if (c.getCodigo() == cargo) {
                                        switch (c.getNome()) {
                                            case "ADM":
                                                p.setVisible(true);
                                                break;
                                            case "CAIXA":
                                                p1.setVisible(true);
                                                break;
                                            case "GARÇOM":
                                                p2.setVisible(true);
                                                break;
                                            case "GERENTE":
                                                p3.setVisible(true);
                                                break;
                                            default:
                                                p2.setVisible(true);
                                                break;

                                        }
                                    }
                                }

                            }
                        });

                    } else {

                        System.out.println("Login incorreto");
                        // senha ou usuario incorreto

                    }
                } else {
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            a.setVisible(false);

                        }
                    });

                    System.out.println("Login incorreto- fora do ar");
                    //servidor fora do ar
                }

            }

            @Override
            public void onFailure(Call<ArrayList<CargoBEAN>> call, Throwable t) {
                //Servidor fora do ar
                JOptionPane.showMessageDialog(null, "Login Incorreto erro");
                System.out.println("Login incorreto");

            }
        });

        dispose();

    }

    private boolean comparar(String cadena) {
        Object[] lista = jtfUsuario.getComponents();
        boolean encontrado = false;
        for (Object object : lista) {
            if (cadena.equals(object)) {
                encontrado = true;
                break;
            }

        }
        return encontrado;
    }

    private SharedPreferencesBEAN fazLogin(String nomeUsuario, String senha) {
        Carregamento a = new Carregamento(FRMLogin.this, true);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                a.setVisible(true);
            }
        });
        RestauranteAPI api = SyncDefault.RETROFIT_RESTAURANTE.create(RestauranteAPI.class
        );
        final Call<SharedPreferencesBEAN> call = api.fazLogin(nomeUsuario, senha);
        SharedPreferencesBEAN u = null;
        System.out.println("1");
        call.enqueue(new Callback<SharedPreferencesBEAN>() {
            @Override
            public void onResponse(Call<SharedPreferencesBEAN> call, Response<SharedPreferencesBEAN> response) {

                if (response.code() == 200) {
                    String auth = response.headers().get("auth");
                    if (auth.equals("1")) {
                        System.out.println("Login correto");
                        SharedPreferencesBEAN u = response.body();

                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                a.setVisible(false);
                                if (u.getFunCargo() > 0) {
                                    if (chekLogado.isSelected()) {
                                        u.setFunSenha(jpfSenha.getText());
                                        c.logIN(u);
                                    }
                                    tipoLogin(u.getFunCargo());
                                } else {
                                    JOptionPane.showMessageDialog(null, "Usuario ainda não confirmado pela empresa");
                                }
                            }
                        });

                    } else {
                        a.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Login Incorreto");
                        System.out.println("Login incorreto");
                        // senha ou usuario incorreto

                    }
                } else {
                    a.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Servidor não responde!!");

                    //servidor fora do ar
                }

            }

            @Override
            public void onFailure(Call<SharedPreferencesBEAN> call, Throwable t) {
                //Servidor fora do ar
                a.setVisible(false);
                JOptionPane.showMessageDialog(null, "Login Incorreto erro");
                System.out.println("Login incorreto");

            }
        });

        return u;

    }

    private void setDados() {
        ControleLogin l = new ControleLogin();
        SharedPreferencesEmpresaBEAN e = l.listarEmpresa();
        if (e != null) {
            lbFantasia.setText(e.getEmpFantazia());
            if (e.getEmpLogo() != null) {
                ManipularImagem m = new ManipularImagem();
                m.exibiImagemLabel(e.getEmpLogo(), lbLogo);
            }
        }
        SharedPreferencesBEAN ll = SharedP_Control.listarLogin();
        if (ll != null) {
            jtfUsuario.setText(ll.getFunEmail());
            jpfSenha.setText(ll.getFunSenha());
        }
    }
}
