/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.VendaControle;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JPanel;
import modelo.VendaAtualBEAN;

/**
 *
 * @author Daniel
 */
public class Mesa extends javax.swing.JPanel {

    private String mesa;
    private String valor;
    private FRMVenda venda = null;
    private FRMCaixa caixa;
    private VendaControle controle;

    public void setCorPainel() {
        Color azul = new Color(92,154,195);
        painel.setBackground(azul);
        
    }
    

    public FRMCaixa getCaixa() {
        return caixa;
    }

    public void setCaixa(FRMCaixa caixa) {
        this.caixa = caixa;
    }

    public FRMVenda getVenda() {
        return venda;
    }

    public void setVenda(FRMVenda venda) {
        this.venda = venda;
    }

    public String getMesa() {
        return mesa;
    }

    public void setMesa(String mesa) {
        this.mesa = mesa;
        labMesa.setText(mesa);
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
        labValor.setText(valor);
    }

    /**
     * Creates new form Mesa
     */
    public Mesa() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        labMesa = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        labValor = new javax.swing.JLabel();

        painel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel.setDoubleBuffered(false);
        painel.setEnabled(false);
        painel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelMouseEntered(evt);
            }
        });

        labMesa.setBackground(new java.awt.Color(255, 255, 255));
        labMesa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labMesa.setForeground(new java.awt.Color(0, 0, 102));
        labMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMesa.setText("07");

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/restaurante.png"))); // NOI18N

        labValor.setBackground(new java.awt.Color(255, 255, 255));
        labValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labValor.setForeground(new java.awt.Color(0, 0, 102));
        labValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labValor.setText("00,00");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(labMesa)
                .addGap(0, 0, 0)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labValor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void painelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseEntered

    }//GEN-LAST:event_painelMouseEntered

    private void painelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseClicked
        controle = new VendaControle();
        if (evt.getClickCount() == 2) {
            FRMListaProdutos l = new FRMListaProdutos();
            l.setDados(mesa);
            l.setVisible(true);       
            
        } else if (venda != null) {
            venda.setNunMesa(mesa);
        } else {
            caixa.setNunMesa(mesa);
           // caixa.atualizaProdutos();
        }
    }//GEN-LAST:event_painelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel labMesa;
    private javax.swing.JLabel labValor;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
